default: &dbconnect
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *dbconnect
  database: violapp_development
  username: violapp_dev
  password: QQdvT4cZAMgYEt6g

test:
  <<: *dbconnect
  database: violapp_test

production:
  <<: *dbconnect
  database: violapp_production
  username: violapp
  password: Kkjhftxi5rckmQuy
